# Generated by Django 2.2.1 on 2020-10-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MicroServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mirror_env', models.CharField(default=None, help_text='环境名称', max_length=100)),
                ('micro_service', models.CharField(default=None, help_text='微服务名称', max_length=100)),
                ('ip_address', models.CharField(default=None, help_text='微服务运行服务器ip', max_length=100)),
                ('root_passwd', models.CharField(default=None, help_text='root用户密码', max_length=100)),
                ('hispace_passwd', models.CharField(default=None, help_text='hispace用户密码', max_length=100)),
                ('ops', models.CharField(default=None, help_text='测试部署负责人', max_length=100)),
                ('Dev', models.CharField(default=None, help_text='开发负责人', max_length=100)),
                ('version', models.CharField(default=None, help_text='版本号', max_length=100)),
                ('branch', models.CharField(default=None, help_text='分支', max_length=100)),
            ],
        ),
    ]
